[workspace]
resolver = "2"
members = ["leptos-routes", "leptos-routes-macro"]
default-members = ["leptos-routes"]

[workspace.package]
version = "0.4.0"
edition = "2024"
rust-version = "1.88"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
repository = "https://github.com/lpotthast/leptos-routes"
license = "MIT OR Apache-2.0"
readme = "./README.md"
